server:
    port: 8081

spring:
    profiles: dev-sql

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/respondeco
        databaseName: respondeco
        serverName: localhost
        username: root
        password:
        cachePrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://test.respondeco.org
        host: mail.respondeco.org
        port: 587
        user: system@respondeco.org
        password: KPfe1mm99Nre443X
        protocol: smtp
        tls: true
        auth: true
        from: system@respondeco.org

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

    social:
        facebook:
            appId: 801386343241847
            appSecret: 0ee624ec572168e2c8af19e4fd870cab
            redirectUrl: http://localhost:9000/#/social-networks
        twitter:
            appId: TXfo29nDCKaU0HmajtEwMhP80
            appSecret: FAvwa7Kjjih9zPWZaDxpfiqQ4ZZ2JfaOi1vXQgtTe4CCUnDeJ6
            redirectUrl: http://127.0.0.1:9000/#/social-networks
        xing:
            appId: b453d9fa070612aba6f6
            appSecret: 9a8bc2effdd97dbdfdd1cc45a10d4cc61d9eb509
            redirectUrl: http://127.0.0.1:9000/#/social-networks
            postBaseUrl: test.respondeco.org/#

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
